image: node:18
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run docs:build
  artifacts:
    paths:
      - .vitepress/dist
  only:
    - main
  tags:
    - test-runner
  publish:
    - .vitepress/dist
